version: '3.3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./.m2:/root/.m2
    working_dir: /app
    command: sh run.sh
    ports:
      - 8080:8080
      - 35729:35729
      - 5005:5005
    environment:
      spring.datasource.url: "jdbc:mysql://db:3306/betoffice"
      spring.datasource.username: "root"
      spring.datasource.password: "root"
      spring.datasource.driver-class-name: "com.mysql.cj.jdbc.Driver"

  db:
    container_name: betoffice_db
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: betoffice
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 33061:3306
    volumes:
      - './docker/db/data:/var/lib/mysql'
      - './docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './docker/db/sql:/docker-entrypoint-initdb.d'
      - './init.sql:/docker-entrypoint-initdb.d/0_init.sql'

